//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class course_exam
    {
        public int id { get; set; }
        [Required]
        public Nullable<int> course_id { get; set; }
        [Required]
        public string have_final_exam { get; set; }
        public Nullable<double> exam_length { get; set; }
        public Nullable<int> required_room_type_id { get; set; }
        public string final_exam_note { get; set; }

        [Display(Name = "Not Current Course?")]
        public Nullable<bool> is_deleted { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    
        public virtual course course { get; set; }
        public virtual room_type room_type { get; set; }
    }
}
