//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamContext : DbContext
    {
        public ExamContext()
            : base("name=ExamContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<course_exam> course_exam { get; set; }
        public virtual DbSet<exam_timetable> exam_timetable { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<program> programs { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<room_type> room_type { get; set; }
        public virtual DbSet<section> sections { get; set; }
        public virtual DbSet<special_arrangement> special_arrangement { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
