//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTable.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class section
    {
        [Display(Name = "ID")]
        public int id { get; set; }

        [Display(Name = "Section")]
        [Required]
        public Nullable<int> section_number { get; set; }

        [Display(Name = "Program")]
        public Nullable<int> program_id { get; set; }

        [Display(Name = "Course")]
        [Required]
        public Nullable<int> course_id { get; set; }

        [Display(Name = "Student Enrolled")]
        //[Required] //remove this because create modelstate is invalid because of null student enrolled...
        public Nullable<int> student_enrolled { get; set; }

        [Display(Name = "Faculty")]
        [Required]
        public Nullable<int> faculty_id { get; set; }

        [Display(Name = "Current Semester?")]
        public Nullable<bool> is_deleted { get; set; }

        [Display(Name = "Created By")]
        public string created_by { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> created_on { get; set; }

        [Display(Name = "Modified By")]
        public string modified_by { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> modified_on { get; set; }

        [Display(Name = "Weekday")]
        public Nullable<int> class_weekday { get; set; }

        [Display(Name = "Start Time")]
        public Nullable<int> class_start_time { get; set; }

        [Display(Name = "Room")]
        public Nullable<int> room_id { get; set; }

        public virtual course course { get; set; }
        public virtual faculty faculty { get; set; }
        public virtual program program { get; set; }
        public virtual room room { get; set; }
    }
}
