//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class special_arrangement
    {
        public int id { get; set; }
        public string program_code { get; set; }
        public string program_title { get; set; }
        public string course_code { get; set; }
        public string course_title { get; set; }
        public Nullable<int> course_hours { get; set; }
        public Nullable<int> section_number { get; set; }
        public string have_final_exam { get; set; }
        public string final_exam_note { get; set; }
        public string room_request { get; set; }
        public string exam_length { get; set; }
        public string weekday { get; set; }
        public string time { get; set; }
        public string room { get; set; }
        public string teacher_name { get; set; }
        public string proctor { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
    }
}
